// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cameras": {
            "get": {
                "description": "Retrieves a list of cameras currently loaded in memory by the C++ workers, including their live runtime status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Get active camera runtime list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/process.Camera"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/add": {
            "post": {
                "description": "Creates a new IP camera in the NVR database using the provided manual data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Add a new manual camera",
                "parameters": [
                    {
                        "description": "Camera creation payload",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CameraDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/db": {
            "get": {
                "description": "Retrieves the complete list of saved cameras directly from the database configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Get database camera list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Camera"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to get db cameras",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/onvif": {
            "post": {
                "description": "Creates a camera by dynamically fetching ONVIF profile tokens and streams using the provided IP and credentials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Add a new ONVIF camera",
                "parameters": [
                    {
                        "description": "ONVIF credentials and payload",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CameraDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get ONVIF data or internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/{cam_id}": {
            "delete": {
                "description": "Delete a camera by its ID. Note that a camera with existing recording data will be rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Delete camera",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "cam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid cam id or development lock",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/{cam_id}/start": {
            "post": {
                "description": "Start camera recording and processing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Activate camera",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "cam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CameraDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid cam id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/cameras/{cam_id}/stop": {
            "post": {
                "description": "Stop camera recording and processing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Deactivate camera",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "cam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CameraDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid cam id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CameraDetailResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "http_port": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "retention_gb_limit": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "supports_ptz": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCameraRequest": {
            "type": "object",
            "required": [
                "ip_address",
                "name",
                "type"
            ],
            "properties": {
                "http_port": {
                    "type": "integer"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "manufacturer": {
                    "description": "Pointers allow JSON \"null\"",
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "description": "Raw password from the UI form!",
                    "type": "string"
                },
                "retention_gb_limit": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "supports_ptz": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "onvif",
                        "rtsp"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Camera": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "http_port": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "onvif_profile_token": {
                    "type": "string"
                },
                "retention_gb_limit": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_profile_token": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "supports_ptz": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "process.Camera": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:9080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NVR Core API",
	Description:      "API for NVR system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
