basePath: /
definitions:
  dto.CameraDetailResponse:
    properties:
      created_at:
        type: integer
      http_port:
        type: integer
      id:
        type: integer
      ip_address:
        type: string
      is_active:
        type: boolean
      mac_address:
        type: string
      mainstream:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      retention_gb_limit:
        type: integer
      serial_number:
        type: string
      substream:
        type: string
      supports_ptz:
        type: boolean
      type:
        type: string
      updated_at:
        type: integer
      username:
        type: string
    type: object
  dto.CreateCameraRequest:
    properties:
      http_port:
        type: integer
      ip_address:
        type: string
      is_active:
        type: boolean
      mainstream:
        type: string
      manufacturer:
        description: Pointers allow JSON "null"
        type: string
      model:
        type: string
      name:
        type: string
      password:
        description: Raw password from the UI form!
        type: string
      retention_gb_limit:
        type: integer
      serial_number:
        type: string
      substream:
        type: string
      supports_ptz:
        type: boolean
      type:
        enum:
        - onvif
        - rtsp
        type: string
      username:
        type: string
    required:
    - ip_address
    - name
    - type
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      permissions:
        items:
          type: string
        type: array
      refresh_token:
        type: string
      token:
        type: string
    type: object
  dto.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RefreshResponse:
    properties:
      permissions:
        items:
          type: string
        type: array
      token:
        type: string
    type: object
  dto.SegmentItem:
    properties:
      camera_id:
        type: integer
      duration_ms:
        type: integer
      end_time:
        type: integer
      id:
        type: integer
      start_time:
        type: integer
      stream_url:
        type: string
    type: object
  dto.SegmentSnapshot:
    properties:
      camera_id:
        type: integer
      end_time:
        type: integer
      id:
        type: integer
      start_time:
        type: integer
      url:
        type: string
    type: object
  dto.TimelineBlock:
    properties:
      end_time:
        type: integer
      start_time:
        type: integer
    type: object
  dto.TimelineResponse:
    properties:
      camera_id:
        type: integer
      segments:
        items:
          $ref: '#/definitions/dto.SegmentItem'
        type: array
      snapshots:
        items:
          $ref: '#/definitions/dto.SegmentSnapshot'
        type: array
      timelines:
        items:
          $ref: '#/definitions/dto.TimelineBlock'
        type: array
    type: object
  dto.UpdateCameraRequest:
    properties:
      http_port:
        type: integer
      ip_address:
        type: string
      is_active:
        type: boolean
      mac_address:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      onvif_profile_token:
        type: string
      password:
        type: string
      retention_gb_limit:
        type: integer
      serial_number:
        type: string
      stream_url:
        type: string
      sub_stream_profile_token:
        type: string
      sub_stream_url:
        type: string
      supports_ptz:
        type: boolean
      type:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
  models.Camera:
    properties:
      created_at:
        type: integer
      http_port:
        type: integer
      id:
        type: integer
      ip_address:
        type: string
      is_active:
        type: boolean
      mac_address:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      onvif_profile_token:
        type: string
      retention_gb_limit:
        type: integer
      serial_number:
        type: string
      stream_url:
        type: string
      sub_stream_profile_token:
        type: string
      sub_stream_url:
        type: string
      supports_ptz:
        type: boolean
      type:
        type: string
      updated_at:
        type: integer
      username:
        type: string
      uuid:
        type: string
    type: object
  onvif.OnvifRecord:
    properties:
      error_msg:
        type: string
      firmware:
        type: string
      in_system:
        type: boolean
      ip:
        type: string
      mac_address:
        type: string
      mainstream:
        description: Streams
        type: string
      mainstream_token:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      serial_number:
        type: string
      substream:
        type: string
      substream_token:
        type: string
      supports_ptz:
        type: boolean
      username:
        description: Camera user/pwd
        type: string
    type: object
  process.Camera:
    properties:
      active:
        type: boolean
      id:
        type: integer
      main_stream:
        $ref: '#/definitions/process.StreamProfile'
      sub_stream:
        $ref: '#/definitions/process.StreamProfile'
    type: object
  process.StreamProfile:
    properties:
      acodec:
        type: integer
      channel_id:
        type: integer
      status:
        description: e.g., "offline", "streaming", "failed"
        type: string
      url:
        type: string
      vcodec:
        type: integer
      worker_id:
        description: Moved here! Can be different for main/sub
        type: integer
    type: object
host: localhost:9080
info:
  contact: {}
  description: API for NVR system.
  title: NVR Core API
  version: "0.1"
paths:
  /api/camera/{id}/onvif:
    get:
      consumes:
      - application/json
      description: Fetch ONVIF camera detail data that is already in our system
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/onvif.OnvifRecord'
        "500":
          description: Failed to get ONVIF data or internal server error
          schema:
            type: string
      summary: Fetch ONVIF data
      tags:
      - Cameras
      - Fetch
  /api/cameras:
    get:
      consumes:
      - application/json
      description: Retrieves a list of cameras currently loaded in memory by the C++
        workers, including their live runtime status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/process.Camera'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get active camera runtime list
      tags:
      - Cameras
  /api/cameras/{cam_id}:
    delete:
      consumes:
      - application/json
      description: Delete a camera by its ID. Note that a camera with existing recording
        data will be rejected.
      parameters:
      - description: Camera ID
        in: path
        name: cam_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: deleted
          schema:
            type: string
        "400":
          description: Invalid cam id or development lock
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete camera
      tags:
      - Cameras
  /api/cameras/{cam_id}/auth:
    put:
      consumes:
      - application/json
      description: Check given credentials, and update if there is no issue.
      parameters:
      - description: Camera creation payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid JSON or missing fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update camera credentials
      tags:
      - Cameras
  /api/cameras/{cam_id}/onvif:
    put:
      consumes:
      - application/json
      description: Creates a camera by dynamically fetching ONVIF profile tokens and
        streams using the provided IP and credentials.
      parameters:
      - description: ONVIF credentials and payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "500":
          description: Failed to get ONVIF data or internal server error
          schema:
            type: string
      summary: Add a new ONVIF camera
      tags:
      - Cameras
  /api/cameras/{cam_id}/start:
    post:
      consumes:
      - application/json
      description: Start camera recording and processing.
      parameters:
      - description: Camera ID
        in: path
        name: cam_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid cam id
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Activate camera
      tags:
      - Cameras
  /api/cameras/{cam_id}/stop:
    post:
      consumes:
      - application/json
      description: Stop camera recording and processing.
      parameters:
      - description: Camera ID
        in: path
        name: cam_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid cam id
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Deactivate camera
      tags:
      - Cameras
  /api/cameras/{cam_id}/timeline/{start}/{end}:
    get:
      description: GetTimeline queries the SQLite database for video segments within
        a time range. And returns continuous recording blocks.
      parameters:
      - description: Camera ID
        in: path
        name: cam_id
        required: true
        type: string
      - description: start time in seconds
        in: path
        name: start
        required: true
        type: string
      - description: end time in seconds
        in: path
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TimelineResponse'
        "400":
          description: Invalid start or end timestamps
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - Timeline
  /api/cameras/{cam_id}/update:
    put:
      consumes:
      - application/json
      description: Creates a new IP camera in the NVR database using the provided
        manual data.
      parameters:
      - description: Camera creation payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid JSON or missing fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add a new manual camera
      tags:
      - Cameras
  /api/cameras/add:
    post:
      consumes:
      - application/json
      description: Creates a new IP camera in the NVR database using the provided
        manual data.
      parameters:
      - description: Camera creation payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid JSON or missing fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add a new manual camera
      tags:
      - Cameras
  /api/cameras/add/onvif:
    post:
      consumes:
      - application/json
      description: Creates a camera by dynamically fetching ONVIF profile tokens and
        streams using the provided IP and credentials.
      parameters:
      - description: ONVIF credentials and payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CameraDetailResponse'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "500":
          description: Failed to get ONVIF data or internal server error
          schema:
            type: string
      summary: Add a new ONVIF camera
      tags:
      - Cameras
  /api/cameras/db:
    get:
      consumes:
      - application/json
      description: Retrieves the complete list of saved cameras directly from the
        database configuration.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Camera'
            type: array
        "500":
          description: Failed to get db cameras
          schema:
            type: string
      summary: Get database camera list
      tags:
      - Cameras
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user by username and password. Returns a short-lived
        JWT access token, a long-lived refresh token, and a list of user permissions.
      parameters:
      - description: User Login Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "401":
          description: Invalid credentials or account disabled
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: User login
      tags:
      - auth
  /api/refresh:
    post:
      consumes:
      - application/json
      description: Exchanges a valid refresh token for a new short-lived JWT access
        token and updated permissions.
      parameters:
      - description: Refresh Token Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully refreshed
          schema:
            $ref: '#/definitions/dto.RefreshResponse'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "401":
          description: Invalid or expired refresh token
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Refresh Access Token
      tags:
      - auth
  /api/scan/{ip}/onvif:
    post:
      consumes:
      - application/json
      description: Fetch ONVIF camera detail data
      parameters:
      - description: ONVIF credentials and payload
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCameraRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/onvif.OnvifRecord'
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "500":
          description: Failed to get ONVIF data or internal server error
          schema:
            type: string
      summary: Fetch ONVIF data
      tags:
      - Cameras
      - Scan
swagger: "2.0"
